### ISSUE TITLE
Simple example is not working on my setup

### ISSUE THREAD

**Issue by KLuka** [OmarShehata/atom-tracer#2]
Hi, I am not able to use this plugin on my Ubuntu 14.04.4 LTS with atom 1.8.0. I installed atom-tracer 0.2.1 from "Install Packages" menu and I always get some errors...

Example file `test.py`:

``` py
x = 3
print x
```

Error:

```
Error parsing JSON output from inject script!
TypeError: Cannot read property 'Result' of undefined
```

**Comment by OmarShehata** [comment]
Thanks for catching and reporting this @KLuka ! I think this is because my plugin relies on [Ink](https://github.com/JunoLab/atom-ink) and I haven't properly declared it as a dependency? 

Can you try to install the Ink package and confirm that this is the problem?

**Comment by KLuka** [comment]
Installing Ink solves the issue.

Thank you and props for nice plugin :+1:
