### ISSUE TITLE
Lang file type support

### ISSUE THREAD

**Issue by TheOdd** [OmarShehata/atom-tracer#8]
So, I'm going to start to try and implement JavaScript into this plugin, and I was wondering if the necessary files in the lang file of the specified language (`info.yml`, `parse.py`, and `inject.py`) have to be in `.py` format. For example, could I write `parse.js` instead of `parse.py` with it still being recognized? I would assume that it only recognizes python files from the way that it is worded, though. If it is only python, would you be open to having other languages supported in handling the variable parsing and injection?

**Comment by TheOdd** [comment]
Nevermind, it seems that it must be in the same language's format. Sorry about that!

**Comment by OmarShehata** [comment]
Sorry for the confusion there @TheOdd ! I most _definitely_ welcome extending this to any (and all) languages and my goal is to make it as easy as possible to do that. 

I added a note in the "how it works" document to clarify that. I'm looking forward to seeing your work on this, don't hesitate to reach out about any other questions or ideas you have!
